"""rename recommendation to overall_condition

Revision ID: 2295bfd2f991
Revises: 62fd4f25361d
Create Date: 2026-07-21 20:33:43.525726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2295bfd2f991'
down_revision: Union[str, Sequence[str], None] = '62fd4f25361d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('overall_condition', sa.Enum('NO_MAJOR_ISSUES', 'MINOR_ISSUES_FOUND', 'MAJOR_ISSUES_FOUND', 'CRITICAL_SAFETY_ISSUES', name='overallcondition', native_enum=False, length=50), nullable=True))
    op.drop_column('inspections', 'recommendation')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.add_column('inspections', sa.Column('recommendation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('inspections', 'overall_condition')
    # ### end Alembic commands ###
