"""add updated_at columns

Revision ID: 62fd4f25361d
Revises: 
Create Date: 2026-07-17 16:47:30.878752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fd4f25361d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_customer_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.drop_constraint(op.f('inspection_fields_category_id_field_name_key'), 'inspection_fields', type_='unique')
    op.drop_index(op.f('idx_results_inspection'), table_name='inspection_results')
    op.drop_index(op.f('idx_results_item'), table_name='inspection_results')
    op.drop_constraint(op.f('inspection_results_inspection_id_inspection_field_id_key'), 'inspection_results', type_='unique')
    op.create_index(op.f('ix_inspection_results_inspection_field_id'), 'inspection_results', ['inspection_field_id'], unique=False)
    op.create_index(op.f('ix_inspection_results_inspection_id'), 'inspection_results', ['inspection_id'], unique=False)
    op.add_column('inspections', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_inspection_customer'), table_name='inspections')
    op.drop_index(op.f('idx_inspection_inspector'), table_name='inspections')
    op.drop_index(op.f('idx_inspection_vehicle'), table_name='inspections')
    op.create_index(op.f('ix_inspections_customer_id'), 'inspections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_user_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_vehicle_registration'), table_name='vehicles')
    op.drop_constraint(op.f('vehicles_registration_number_key'), 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.create_unique_constraint(op.f('vehicles_registration_number_key'), 'vehicles', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_vehicle_registration'), 'vehicles', ['registration_number'], unique=False)
    op.drop_column('vehicles', 'updated_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_customer_id'), table_name='inspections')
    op.create_index(op.f('idx_inspection_vehicle'), 'inspections', ['vehicle_id'], unique=False)
    op.create_index(op.f('idx_inspection_inspector'), 'inspections', ['inspector_id'], unique=False)
    op.create_index(op.f('idx_inspection_customer'), 'inspections', ['customer_id'], unique=False)
    op.drop_column('inspections', 'updated_at')
    op.drop_index(op.f('ix_inspection_results_inspection_id'), table_name='inspection_results')
    op.drop_index(op.f('ix_inspection_results_inspection_field_id'), table_name='inspection_results')
    op.create_unique_constraint(op.f('inspection_results_inspection_id_inspection_field_id_key'), 'inspection_results', ['inspection_id', 'inspection_field_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_results_item'), 'inspection_results', ['inspection_field_id'], unique=False)
    op.create_index(op.f('idx_results_inspection'), 'inspection_results', ['inspection_id'], unique=False)
    op.create_unique_constraint(op.f('inspection_fields_category_id_field_name_key'), 'inspection_fields', ['category_id', 'field_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('idx_customer_phone'), 'customers', ['phone'], unique=False)
    op.drop_column('customers', 'updated_at')
    # ### end Alembic commands ###
